dbt_project:
  outputs:
    dev:
      dataset: retail_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/airflow/gcp/service_account.json
      location: US
      method: service-account
      priority: interactive
      project: ornate-chemist-425808-e2
      threads: 1
      type: bigquery
  target: dev